apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendservice
spec:
  selector:
    matchLabels:
      app: backendservice
  template:
    metadata:
      labels:
        app: backendservice
    spec:
      serviceAccountName: appmod-ksa
      containers:
        - name: server
          image: gcr.io/techub-demos-host/backendservice:v2.1
          ports:
          - containerPort: 50052
          env:
          - name: PROJECT_ID
            value: "techub-demos-host"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backendservice
spec:
  type: ClusterIP
  selector:
    app: backendservice
  ports:
  - name: grpc
    port: 50052
    targetPort: 50052
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: appmod-ksa
      containers:
        - name: server
          image: gcr.io/techub-demos-host/frontend:v2.0
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: BACKEND_SERVICE_ADDR
            value: "backendservice:50052"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
