# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Adapted from https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/kubernetes-manifests/frontend.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolitichapp
spec:
  selector:
    matchLabels:
      app: monolothicapp
  template:
    metadata:
      labels:
        app: monolothicapp
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: appmod-ksa
      containers:
        - name: server
          image: gcr.io/techub-demos-host/monolothicapp:v1.0
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: PROJECT_ID
            value: "techub-demos-host"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: monolothicapp
spec:
  type: ClusterIP
  selector:
    app: monolothicapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: monolothicapp-external
spec:
  type: LoadBalancer
  selector:
    app: monolothicapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
